version: '2'

services:
  gestor_inventario:
    image: local/yiisoftware/yii2-php:7.3-apache
    volumes:
      - ../:/app
    ports:
      - '8000:80'
    networks:
      - backend
    environment:
      DB_HOST: 'gestor_inventario_db'
      DB_NAME: 'gestorinventario'
    labels:
     - "traefik.backend=gestor-inventario"
     - "traefik.frontend.rule=Host:api.gestor-inventario.local"
     - "traefik.port=80"

  gestor_inventario_db:
    image: mariadb:10.4
    restart: always
    volumes:
     - ./../../dbdata:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
     - 3306:3306
    networks:
      - backend

##### LUGAR

#  lugar:
#    image: php_yii_ds
#    volumes:
#      - /app/desarrollo-social/lugar/backend-lugar:/var/www/html
#    environment:
#      DB_HOST: 'lugar_db'
#      DB_NAME: 'lugar'
#    labels:
#     - "traefik.backend=lugar"
#     - "traefik.frontend.rule=Host:lugar.local"
#     - "traefik.port=80"
#
#  lugar_db:
#    image: mariadb:10.4
#    ports:
#     - 3309:3306
#    environment:
#     MYSQL_ROOT_PASSWORD: root
#     MYSQL_ROOT_HOST: '%'
#    volumes:
#     - /app/desarrollo-social/lugar/dbdata:/var/lib/mysql
    

##### PROXY

  proxy:
    image: traefik:1.7.6
    restart: always
    command: --web --docker --docker.domain=local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/proxy/traefik.toml:/etc/traefik/traefik.toml
    labels:
     - "traefik.backend=proxy"
     - "traefik.frontend.rule=Host:proxy.local"
     - "traefik.port=8080"
    networks:
      - backend
     
networks:
  backend:
